apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: carts-db
  namespace: sock-shop
spec:
  podSelector:
    matchLabels:
      name: carts-db
  listeners:
    - portMapping:
        port: 27017
        protocol: tcp
  serviceDiscovery:
    dns:
      hostname: carts-db.sock-shop.svc.cluster.local
  logging:
    accessLog:
      file:
        path: "/dev/stdout"
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: carts-db
  namespace: sock-shop
spec:
  awsName: carts-db.sock-shop.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: carts-db
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: sock-shop
  name: carts-db
spec:
  listeners:
    - portMapping:
        port: 27017
        protocol: tcp
  routes:
    - name: carts-db
      priority: 10
      tcpRoute:
        match:
          port: 27017
        action:
          weightedTargets:
            - virtualNodeRef:
                name: carts-db
              weight: 100
        retryPolicy:
          maxRetries: 3
          perRetryTimeout:
            unit: s
            value: 2000
