---
apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop
  labels:
    mesh: sock-shop
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: sock-shop
spec:
  namespaceSelector:
    matchLabels:
      mesh: sock-shop
  egressFilter:
    type: ALLOW_ALL
