apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: shipping
  namespace: sock-shop
spec:
  podSelector:
    matchLabels:
      name: shipping
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: shipping.sock-shop.svc.cluster.local
  logging:
    accessLog:
      file:
        path: "/dev/stdout"
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: shipping
  namespace: sock-shop
spec:
  awsName: shipping.sock-shop.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: shipping
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: sock-shop
  name: shipping
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
  routes:
    - name: shipping
      priority: 10
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: shipping
              weight: 100
