apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: catalogue
    #namespace: sock-shop
  annotations:
    multicluster.x-k8s.io/aws-vpc: "vpc-00787224395bd845c"    
    multicluster.x-k8s.io/aws-eks-cluster-name: "xiangyan-lattice-2"
spec:
  type: ClusterSetIP
  ports:
  - port: 80
    protocol: HTTP
